export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
// export const DASHBOARD_ROUTE = '/dashboard'
export const CALENDAR_ROUTE = '/calendar'
export const TASKS_ROUTE = '/tasks'
export const DASHBOARD_ROUTE = '/dashboard'
export const SETTING_ROUTE = '/setting'
